### ISSUE TITLE
Is my CC2652RB fried?

### ISSUE THREAD

**Issue by DrTron** [slaesh/cc2652-stick#25]
All,

Just overnight my zigbee2mqtt crashed. Trying to restart it results in the CC2652RB stick not being accessible.
I can flash it with firmware (currently CC2652RB_coordinator_20230507.hex) and it shows up correctly under "/dev". No errors in dmesg either.

However, the coordinator-test crashes, too, and only shows this:
```
Opening port /dev/ttyUSB0, baud 115200

*** sending synch sequence
---> 00: 00 (0)
---> 01: 00 (0)
---> 02: 00 (0)
---> 03: cc (204)
Got 0 additional bytes before ACK/NACK
*** GetChipId command (0x28)
---> 00: 00 (0)
---> 01: 00 (0)
---> 02: 00 (0)
---> 03: cc (204)
Got 0 additional bytes before ACK/NACK
*** received 6 bytes
---> 00: 06 (6)
---> 01: 23 (35)
###
---> 00: 31 (49)
---> 01: 02 (2)
---> 02: f0 (240)
---> 03: 00 (0)
*** GetStatus command (0x23)
---> 00: 00 (0)
---> 01: 00 (0)
---> 02: 00 (0)
---> 03: cc (204)
Got 0 additional bytes before ACK/NACK
*** received 3 bytes
---> 00: 03 (3)
---> 01: 40 (64)
###
---> 00: 40 (64)
Command Successful
    Version 0x3102F000
--> Bootloader is working!
*** received 0
The Array is:  bytearray(b'')
*** received 0
*** received 0
*** received 0
*** ReadFwVersion cmd
*** received 0
*** received 0
*** received 0
The Array is:  bytearray(b'')
*** received 0
*** received 0
*** received 0
*** ReadFwVersion cmd
*** received 0
*** received 0
Traceback (most recent call last):
  File "/install/CC2652RB/cc2652-stick/coordinator-test/./test.py", line 540, in <module>
    cmd.cmdReadFwVersion()
  File "/install/CC2652RB/cc2652-stick/coordinator-test/./test.py", line 350, in cmdReadFwVersion
    raise CmdException("to small")
CmdException: to small

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/install/CC2652RB/cc2652-stick/coordinator-test/./test.py", line 542, in <module>
    cmd.cmdReadFwVersion()
  File "/install/CC2652RB/cc2652-stick/coordinator-test/./test.py", line 350, in cmdReadFwVersion
    raise CmdException("to small")
CmdException: to small
ERROR: to small
```
Any ideas short of buying another stick?
Thanks!

**Comment by DrTron** [comment]
In case anyone ever reads this because of the same problem: yes, it looks like the coordinator died. Ordered a new one, flashed it and it's working.

**Comment by vicfergar** [comment]
I had the same issue described here. The firmware got corrupted for some reason during a blackout, causing the test script to fail with the same error. Re-flashing the correct firmware brought it back to life.
